# Use the official lightweight Alpine-based NGINX image as the base image
FROM nginx:alpine

# Copy the custom NGINX configuration file into the container
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Start NGINX in the foreground to keep the container running
CMD ["nginx", "-g", "daemon off;"]
