apiVersion: v1         # Defines the API version for managing Service resources
kind: Service          # Specifies that this resource is a Service
metadata:
  name: streamlit-ui  # Unique name for the Service
spec:
  selector:
    app: streamlit-ui  # Label selector used to match the pods targeted by this Service
  ports:
    - protocol: TCP    # Network protocol used by the Service
      port: 8501       # Port on which the Service is exposed
      targetPort: 8501 # Port on the container to which traffic is forwarded
